# Generated by Django 6.0.3 on 2026-04-19 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(related_name='exercises', to='workouts.category'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workout'),
        ),
    ]
